This is makeindex, version 2.15 [MiKTeX 2.9] (kpathsea + Thai support).
Scanning style file H:/Users/Joren/Documents/GitHub/VHDL/Thesis/LaTeX/thesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file thesis.acn....done (49 entries accepted, 0 rejected).
Sorting entries....done (284 comparisons).
Generating output file thesis.acr....done (59 lines written, 0 warnings).
Output written in thesis.acr.
Transcript written in thesis.alg.
